version: 2
secret:
  ignored_paths:
    - ".env.example"
    - "tests/**"
    - "package_control_channel/**"
  validity:
    # Optional: require a bit of entropy before flagging
    minimum_entropy: 3.5
