repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
      - id: bandit
        name: bandit (security static analysis)
        args: ["-q", "-r", "app", "--severity-level", "medium", "--confidence-level", "high"]
        files: ^app/.*\.py$
        pass_filenames: false