[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = '''
^(
  package_control_channel/|
  \.venv/|
  build/|
  dist/|
  node_modules/|
  .*/migrations/
)
'''

[tool.isort]
profile = "black"
line_length = 100
skip_glob = [
  "package_control_channel/**",
  ".venv/**",
  "build/**",
  "dist/**",
  "node_modules/**",
]

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = [
  "package_control_channel/**",
  ".venv/**",
  "build/**",
  "dist/**",
  "node_modules/**",
  "*/migrations/**",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = [
  "UP046",  # Keep Generic[...] for compatibility with Python < 3.12 (PEP 695 not available)
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
