[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = '''
^(
  package_control_channel/|
  \.venv/|
  build/|
  dist/|
  node_modules/|
  .*/migrations/
)
'''

[tool.isort]
profile = "black"
line_length = 100
skip_glob = [
  "package_control_channel/**",
  ".venv/**",
  "build/**",
  "dist/**",
  "node_modules/**",
]

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = [
  "package_control_channel/**",
  ".venv/**",
  "build/**",
  "dist/**",
  "node_modules/**",
  "*/migrations/**",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = [
  "UP046",  # Keep Generic[...] for compatibility with Python < 3.12 (PEP 695 not available)
]

[tool.pytest.ini_options]
addopts = "--tb=short -v"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
markers = [
    "anyio: marks tests as needing anyio (deselect with '-m \"not anyio\"')",
    "asyncio: marks tests as needing asyncio",
]
# Use only asyncio backend for stability in CI environments
# (configured via ANYIO_BACKEND environment variable)
