name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    env:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      TESTING: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select TEST_BYPASS_TOKEN (secret if available, else default)
        run: echo "TEST_BYPASS_TOKEN=${TOKEN:-test-bypass-ci}" >> "$GITHUB_ENV"
        env:
          TOKEN: ${{ secrets.TEST_BYPASS_TOKEN }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint & security (pre-commit)
        run: pre-commit run --all-files

      - name: Tests
        run: pytest -q