name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip

      - name: Install deps
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint & format
        run: |
          source .venv/bin/activate
          ruff check .
          black --check .
          isort --check-only .

      - name: Start server
        run: |
          source .venv/bin/activate
          export ALLOW_ARBITRARY_SHELL_COMMANDS=true
          export SHELL_ALLOWLIST="ls,cat,echo"
          uvicorn app.main:app --port 8000 &
          sleep 2

      - name: Run tests
        env:
          PYTHONPATH: .
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "true"
          ANYIO_BACKEND: "asyncio"
        run: |
          source .venv/bin/activate
          # Only run asyncio tests in CI to avoid event loop issues
          pytest -q
