name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          # requirements.txt is optional in your repo
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt

      - name: Lint (ruff)
        run: make lint

      - name: Typecheck (mypy)
        run: make typecheck

      - name: Tests (starts/stops uvicorn)
        env:
          WAIT_SECS: 60
          LOG_LEVEL: INFO
          ADMIN_USERNAME: admin
          ADMIN_PASSWORD: admin123
          PYTHONPATH: .
        run: make test

      # Optional: secured flow tests (enable when needed)
      # - name: Auth Flow Tests
      #   env:
      #     WAIT_SECS: 60
      #     RUN_AUTH_TESTS: "1"
      #     LOG_LEVEL: INFO
      #     ADMIN_USERNAME: admin
      #     ADMIN_PASSWORD: admin123
      #   run: make test
